# Generated by Django 6.0.7 on 2026-09-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astra', '0030_utilisateur_alter_client_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='prenom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
