# Generated by Django 6.0.7 on 2026-09-11 11:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astra', '0031_client_prenom'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('fournisseur', 'Fournisseur'), ('stocks', 'Gestionnaire de stock'), ('approvisionnement', 'Approvisionnement'), ('rapports', 'Rapports'), ('vente', 'Vente'), ('admin', 'Administrateur')], default='client', max_length=50),
        ),
        migrations.AlterField(
            model_name='utilisateuracces',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('fournisseur', 'Fournisseur'), ('stocks', 'Gestionnaire de stock'), ('approvisionnement', 'Approvisionnement'), ('rapports', 'Rapports'), ('vente', 'Vente'), ('admin', 'Administrateur')], max_length=50),
        ),
    ]
