"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Chargement du fichier .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ==================================================
# SECURITY
# ==================================================

SECRET_KEY = os.getenv("SECRET_KEY")

DEBUG = os.getenv("DEBUG") == "True"

# Autorise les connexions locales et depuis d'autres appareils du réseau pour les tests
ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    "http://192.168.0.119:8000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://*.serveousercontent.com",
    "https://*.serveo.net",
]

# ==================================================
# APPLICATIONS
# ==================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Applications ASTRA TECH
    'astra',
    'boutique',
]

# ==================================================
# MIDDLEWARE
# ==================================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Sert les fichiers statiques en production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'astra.middleware.VerrouillageGlobalMiddleware', # 👈 Commenté pour le test
]

# ==================================================
# URL CONFIGURATION
# ==================================================

ROOT_URLCONF = 'config.urls'

# ==================================================
# TEMPLATES
# ==================================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request', # Requis pour l'admin et vos vérifications d'URL
                'django.contrib.auth.context_processors.auth', # Requis pour l'authentification admin
                'django.contrib.messages.context_processors.messages', # Requis pour les messages admin
                'astra.context_processors.notifications_processor',
            ],
        },
    },
]
WSGI_APPLICATION = 'config.wsgi.application'

# ==================================================
# DATABASE
# ==================================================

_TURSO_URL = os.getenv('TURSO_DATABASE_URL')
_TURSO_TOKEN = os.getenv('TURSO_AUTH_TOKEN')

if _TURSO_URL:
    # Production (Vercel Turso/libSQL)
    DATABASES = {
        'default': {
            'ENGINE': 'django_libsql',
            'NAME': _TURSO_URL,
            'AUTH_TOKEN': _TURSO_TOKEN,
            'OPTIONS': {
                'timeout': 30,
            },
        }
    }
else:
    # Développement local : SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# ==================================================
# PASSWORD VALIDATION
# ==================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ==================================================
# INTERNATIONALIZATION
# ==================================================

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Africa/Douala'

USE_I18N = True

USE_TZ = True

# ==================================================
# STATIC FILES (CSS / JS / IMAGES)
# ==================================================

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# WhiteNoise : compression + cache long terme des fichiers statiques
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ==================================================
# MEDIA FILES (images uploadées)
# ==================================================

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / "media"

# ==================================================
# EMAIL SMTP GMAIL
# ==================================================

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = os.getenv("EMAIL_HOST")

EMAIL_PORT = int(os.getenv("EMAIL_PORT") or 587)

EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS") == "True"

EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")

EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")

DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")

# ==================================================
# AUTHENTIFICATION & SESSIONS
# ==================================================

# Harmonisé sur 'login' pour correspondre aux templates et routes
LOGIN_URL = "astra:login"

LOGIN_REDIRECT_URL = "astra:accueil"

LOGOUT_REDIRECT_URL = "astra:login"

# Paramètres pour assurer la stabilité des sessions entre navigateurs
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 1209600  # 2 semaines
SESSION_SAVE_EVERY_REQUEST = True